name: Generate Explanation and Add Comment

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  generate_explanation_and_add_comment:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
      
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      
    - name: Run Code and Generate Explanation
      id: explanation
      env:
        POC_API_KEY: ${{ secrets.POC_API_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: |
        explanation=$(python generate_explanation.py)
        echo "::set-output name=explanation::${explanation}"
      
    - name: Add Comment to Pull Request
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const explanation = '${{ steps.explanation.outputs.explanation }}';
          const octokit = github.getOctokit(process.env.GITHUB_TOKEN);
          const { owner, repo } = github.context.repo;
          const { number } = github.context.payload.pull_request;
          octokit.issues.createComment({
            owner: owner,
            repo: repo,
            issue_number: number,
            body: explanation
          });
