name: Generate Explanation and Add Comment

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  generate_explanation_and_add_comment:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
      
    - name: Install openai module
      run: |
        pip install openai
      
    - name: Run Code and Generate Explanation
      id: explanation
      env:
        POC_API_KEY: ${{ secrets.POC_API_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: |
        explanation=$(python generate_explanation.py)
        echo "::set-output name=explanation::${explanation}"
      
    - name: Add Comment to Pull Request
      uses: actions/github-script@3
      with:
        script: |
          const github = context.repo;
          const issue_number = context.payload.pull_request.number;
          const body = `${{ steps.explanation.outputs.explanation }}`;
          github.issues.createComment({
            ...github,
            issue_number,
            body
          });
