name: Add Comment to Pull Request

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  chatgpt_add_comment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai
          pip install PyGithub

      - name: Generate explanation
        id: explanation
        env:
          POC_API_KEY: ${{ secrets.POC_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          python generate_explanation.py > explanation.txt
          echo "::set-output name=explanation::$(cat explanation.txt)"

      - name: Add Comment to Pull Request
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { Octokit } = require("@octokit/rest");
            const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });

            const comment = `Explanation of Changes (powered by chatgpt):\n\n${{ steps.explanation.outputs.explanation }}`;

            async function run() {
              const newComment = await octokit.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: comment
              });

              console.log(`Comment added: ${newComment.data.html_url}`);
            }

            run();

